spring:
  application:
    name: 09_unittesting
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

logging:
  pattern:
    console: %green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
