
 Basic shortcuts for Intellij IDE.
 Shortcut functionality starts with "-", the line below is a list of all available, until you found a empty line.


- Basic Completion
Ctrl+Space

- SmarCompletion
Ctrl+Shift+Space

- Statment completion
Ctrl+Shift+Enter

- Postfix Completion
Ctrl+J

- HippiCompletion
Alt+/       name(Alt+/)

- Expand
Ctrl + Numpag +

- Expand All
Ctrl +Shift+ Numpag +


- Collapse code block
	Ctrol + Numpad -
	Ctrol + Numpad +
	
- Fixed or Suggestion to fixed
	Alt + Enter

- Project Settings
Ctrl+Alt+Shift+S

- Intellij  Settings
Ctrl+Alt+S

- Go to Error
Shift+F2

- Make Local Variable
Alt-Shift+V

- To navigate to the last edited location
Ctrl+Shift+Backspace 

- Format Code
Shift + Alt + L


- Quick Documentation Reference
Ctrl + Q

- Extract Method & Create Method Based on Highlight
Ctrl + Alt + M

- Go Back to Last Line view
Ctrl + Alt + Left

- Generate Code (Getter,Setter,Constructor)
Alt + Insert
 
- Generate Override methods
Ctrl + O

- Remove Unused Imports / Optimized Imports
Ctrl + Alt + O

- Run Local Class
Ctrl + Shift + F10

- Duplicate Line
Ctrl + D

- Parameter Info (what a method spects)
Ctrl + Alt + Space
Ctrl + P

- File Structure / Analyze Object
Ctrl + 0

- Add Break Point
Ctrl + 8]