spring:
  application:
    name: mcpserverremote
  ai:
    # OPENAI
#    openai:
#      api-key: ${OPENAI_API_KEY}
#  main:
#    web-application-type:
#    banner-mode: off
  datasource:
    url: jdbc:h2:file:./chatmemory
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
# Configure log colors
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p){yellow} %clr([%15.15t]){green} %clr(%-40.40logger{39}){cyan} %clr(:){red} %m%n"
server:
  port: 8090
